In [2]:
import pandas as pd

In [3]:
nba2006 = pd.read_csv('./2006-2007_NBA_Box_Score_Team_Stats.csv')

In [6]:
nba2006.head().T

,0,1,2,3,4
DATASET,2006-2007 Regular Season,2006-2007 Regular Season,2006-2007 Regular Season,2006-2007 Regular Season,2006-2007 Regular Season
DATE,10/31/06,10/31/06,10/31/06,10/31/06,11/01/06
TEAMS,Chicago,Miami,Phoenix,LA Lakers,Indiana
VENUE,Road,Home,Road,Home,Road
1Q,22,16,41,26,23
2Q,37,14,17,27,26
3Q,21,21,21,34,28
4Q,28,15,27,27,29
OT1,NaN,NaN,NaN,NaN,NaN
OT2,NaN,NaN,NaN,NaN,NaN
OT3,NaN,NaN,NaN,NaN,NaN
OT4,NaN,NaN,NaN,NaN,NaN
F,108,66,106,114,106
MIN,240,240,240,240,240
FG,39,25,40,46,35
FGA,79,65,77,83,86
3P,7,3,13,6,6
3PA,13,17,30,12,16
FT,23,13,13,16,30
FTA,32,22,17,24,41
OR,13,4,4,12,18
DR,36,25,25,31,32
TOT,49,29,29,43,50
A,22,13,29,30,26
PF,21,24,25,19,26
ST,10,6,7,11,14
TO,16,21,21,20,17
BL,5,3,5,1,5
PTS,108,66,106,114,106
POSS,91.8,91.8,100,100,101.2
PACE,91.8,91.8,100,100,101.2
OEFF,117.6,71.9,106,114,104.7
DEFF,71.9,117.6,114,106,97.8
REST DAYS,3+,3+,3+,3+,3+
STARTING LINEUPS,P. Brown,U. Haslem,R. Bell,A. Bynum,D. Granger
Unnamed: 35,L. Deng,S. O'Neal,B. Diaw,L. Odom,A. Harrington
Unnamed: 36,B. Gordon,G. Payton,S. Marion,S. Parker,S. Jackson
Unnamed: 37,K. Hinrich,D. Wade,S. Nash,S. Vujacic,J. O'Neal
Unnamed: 38,B. Wallace,A. Walker,K. Thomas,L. Walton,J. Tinsley
MAIN REFEREE,Not available,NaN,Steve Javie,NaN,David Jones
CREW REFEREES,Bernie Fryer,Derek Richardson,Tom Washington,Eric Lewis,Eli Roe
OPENING ODDS,193,-6,-6,205,-3
SPREAD,6,-6,-6,6,-3
TOTAL,193,193,205,205,194
MOVEMENTS,188.5/187.5/187,-6/-5.5/-5,-8/-8-15/-8.5,207.5/207/206.5,PK/-1/PK
CLOSING,186.5,-4.5,-8-15,207,-1
MONEYLINE,170,-200,-380,310,NaN
HALFTIME,NaN,NaN,NaN,NaN,NaN
BOX SCORE,NaN,Boxscore,NaN,Boxscore,NaN
ODDS,NaN,Odds,NaN,Odds,NaN

In [5]:
nba2006.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2619 entries, 0 to 2618
Data columns (total 50 columns):
DATASET             2618 non-null object
DATE                2618 non-null object
TEAMS               2618 non-null object
VENUE               2618 non-null object
1Q                  2618 non-null float64
2Q                  2618 non-null float64
3Q                  2618 non-null float64
4Q                  2618 non-null float64
OT1                 180 non-null float64
OT2                 34 non-null float64
OT3                 2 non-null float64
OT4                 0 non-null float64
F                   2618 non-null float64
MIN                 2618 non-null float64
FG                  2618 non-null float64
FGA                 2618 non-null float64
3P                  2618 non-null float64
3PA                 2618 non-null float64
FT                  2618 non-null float64
FTA                 2618 non-null float64
OR                  2618 non-null float64
DR                  2618 non-null float64
TOT                 2618 non-null float64
A                   2618 non-null float64
PF                  2618 non-null float64
ST                  2618 non-null float64
TO                  2618 non-null float64
BL                  2618 non-null float64
PTS                 2618 non-null float64
POSS                2618 non-null float64
PACE                2618 non-null float64
OEFF                2618 non-null float64
DEFF                2618 non-null float64
REST DAYS           2618 non-null object
STARTING LINEUPS    2618 non-null object
Unnamed: 35         2618 non-null object
Unnamed: 36         2618 non-null object
Unnamed: 37         2618 non-null object
Unnamed: 38         2617 non-null object
MAIN REFEREE        1309 non-null object
CREW REFEREES       2618 non-null object
OPENING ODDS        2618 non-null object
SPREAD              2618 non-null float64
TOTAL               2618 non-null float64
MOVEMENTS           2550 non-null object
CLOSING             2618 non-null object
MONEYLINE           2218 non-null float64
HALFTIME            0 non-null float64
BOX SCORE           1309 non-null object
ODDS                1309 non-null object
dtypes: float64(33), object(17)
memory usage: 1023.1+ KB

### NBA csv File Structure

Currently, the NBA data has two records for each game one with the home team data and one with the away team data.  The unit of analysis for this study is the game so the data needs to be rearranged to use the game as the unit of analysis.  Therefore, each even row must be appended to the odd row above it to make the game the unit of analysis

In [31]:


def merge_home_away(df):
    
    #make all column names lower snake case
    df.columns = [col.lower().replace(' ', '_') for col in df.columns]
    
    #split up the rows
    df1 =  df[df.index %2 == 1]
    df2 = df[df.index %2 == 2] 
    
    #drop redunant columns in df2
    df2.drop(columns = ['dataset','date','venue'], inplace = True)
    
    #rename columns df2 
    df2.rename(columns = {'teams'   : 'away_team',
                          '1q'      : '1q_away',
                          '2q'      : '2q_away',
                          '3q'      : '3q_away',
                          '4q'      : '4q_away',
                          'ot1'     : 'ot1_away',
                          'ot2'     : 'ot2_away',
                          'ot3'     : 'ot3_away',
                          'ot4'     : 'ot4_away',
                          'f'       : 'away_score',
                          'min'     : 'away_min',
                          'fg'      : 'away_fg',
                          'fga'     : 'away_fga',
                          
                          
        
    }, inplace = True)
    
    
    #join them back on axis 1
    return pd.concat([df1,df2], axis = 1)

In [32]:
merge_home_away(nba2006).info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1309 entries, 1 to 2617
Data columns (total 97 columns):
dataset             1309 non-null object
date                1309 non-null object
teams               1309 non-null object
venue               1309 non-null object
1q                  1309 non-null float64
2q                  1309 non-null float64
3q                  1309 non-null float64
4q                  1309 non-null float64
ot1                 90 non-null float64
ot2                 17 non-null float64
ot3                 1 non-null float64
ot4                 0 non-null float64
f                   1309 non-null float64
min                 1309 non-null float64
fg                  1309 non-null float64
fga                 1309 non-null float64
3p                  1309 non-null float64
3pa                 1309 non-null float64
ft                  1309 non-null float64
fta                 1309 non-null float64
or                  1309 non-null float64
dr                  1309 non-null float64
tot                 1309 non-null float64
a                   1309 non-null float64
pf                  1309 non-null float64
st                  1309 non-null float64
to                  1309 non-null float64
bl                  1309 non-null float64
pts                 1309 non-null float64
poss                1309 non-null float64
pace                1309 non-null float64
oeff                1309 non-null float64
deff                1309 non-null float64
rest_days           1309 non-null object
starting_lineups    1309 non-null object
unnamed:_35         1309 non-null object
unnamed:_36         1309 non-null object
unnamed:_37         1309 non-null object
unnamed:_38         1308 non-null object
main_referee        0 non-null object
crew_referees       1309 non-null object
opening_odds        1309 non-null object
spread              1309 non-null float64
total               1309 non-null float64
movements           1271 non-null object
closing             1309 non-null object
moneyline           1109 non-null float64
halftime            0 non-null float64
box_score           1309 non-null object
odds                1309 non-null object
away_team           0 non-null object
1q_away             0 non-null float64
2q_away             0 non-null float64
3q_away             0 non-null float64
4q_away             0 non-null float64
ot1_away            0 non-null float64
ot2                 0 non-null float64
ot3                 0 non-null float64
ot4                 0 non-null float64
f                   0 non-null float64
min                 0 non-null float64
fg                  0 non-null float64
fga                 0 non-null float64
3p                  0 non-null float64
3pa                 0 non-null float64
ft                  0 non-null float64
fta                 0 non-null float64
or                  0 non-null float64
dr                  0 non-null float64
tot                 0 non-null float64
a                   0 non-null float64
pf                  0 non-null float64
st                  0 non-null float64
to                  0 non-null float64
bl                  0 non-null float64
pts                 0 non-null float64
poss                0 non-null float64
pace                0 non-null float64
oeff                0 non-null float64
deff                0 non-null float64
rest_days           0 non-null object
starting_lineups    0 non-null object
unnamed:_35         0 non-null object
unnamed:_36         0 non-null object
unnamed:_37         0 non-null object
unnamed:_38         0 non-null object
main_referee        0 non-null object
crew_referees       0 non-null object
opening_odds        0 non-null object
spread              0 non-null float64
total               0 non-null float64
movements           0 non-null object
closing             0 non-null object
moneyline           0 non-null float64
halftime            0 non-null float64
box_score           0 non-null object
odds                0 non-null object
dtypes: float64(66), object(31)
memory usage: 1002.2+ KB

/Users/bryancombs/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/Users/bryancombs/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:3027: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)